### ISSUE TITLE
make Ultimaker platform compatible with HA OS 5.12

### ISSUE THREAD

**Issue by danieledge** [jellespijker/home-assistant-ultimaker#10]
I’m trying to set up the integration with an UltimakerS5

However no devices or entities get created..

Not sure where I could be going wrong:

sensor:
  - platform: ultimaker
    name: UltimakerS5
    host: 172.24.1.109
    scan_interval: 10  # optional, default 10
    decimal: 2  # optional, default 2 rounds the sensor values
    sensors:
      - status  # optional
      - state  # optional
      - progress  # optional
      - bed_type  # optional
      - bed_temperature  # optional
      - bed_temperature_target  # optional
      - hotend_1_id  # optional
      - hotend_1_temperature  # optional
      - hotend_1_temperature_target  # optional
      - hotend_2_id  # optional
      - hotend_2_temperature  # optional
      - hotend_2_temperature_target  # optional

**Comment by jellespijker** [comment]
I see that you're using `hotend_1_id`, `hotend_2_id` and `bed_type`. These are changes that I released today. Make sure that you're using the latest version `0.1.4` or `master` when you use these.

You could check if it stumbles over the comments `#`. Try removing them. It can't hurt to make the name lower case as well. If that is the case please let me know. So I can update the README.md.

```yaml
sensor:
  - platform: ultimaker
    name: ultimakers5
    host: 172.24.1.109
    scan_interval: 10
    sensors:
      - status
      - state
      - progress
      - bed_temperature
      - bed_temperature_target
      - bed_type
      - hotend_1_id
      - hotend_1_temperature
      - hotend_1_temperature_target
      - hotend_2_id
      - hotend_2_temperature
      - hotend_2_temperature_target
```

This should create multiple sensors: such as `sensor.ultimakers5_hotend_1_temperature`
If this still not works you can output debugging log entries  if you create the following entry in your `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    custom_components.ultimaker: debug
```
This should give you additional information. Remember to remove it afterwards or change the `debug` to `info`, otherwise, your log file will be very big.

I need additional information if it still doesn't work. Like your log file. Used version, both from HA and this plugin.
